root: true
extends:
  - remcohaszing
  - remcohaszing/typechecking
rules:
  '@typescript-eslint/no-unsafe-assignment': off
  '@typescript-eslint/no-unsafe-call': off
overrides:
  - files:
      - '*.md/*'
    rules:
      '@typescript-eslint/no-unused-vars': off
